version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=dynamodb
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
    ports:
      - "4510-4559:4510-4559"
      - "4566:4566"
    volumes:
      - "./localstack:/docker-entrypoint-initaws.d"
      - "/var/run/docker.sock:/var/run/docker.sock"